import { TooltipProvider } from '@/components/ui/tooltip';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
export const metadata: Metadata = {
	title: "AskBard.ai",
	description: "Generated by create next app",
	icons: {
        icon: '/favicon.png',
    },
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={inter.variable}>
			<body className="antialiased">
				<TooltipProvider>
					{children}
				</TooltipProvider>
			</body>
		</html>
	);
}
